### PR TITLE
Added elementPrefix option + docs

### PR DESCRIPTION
**Pull request by wclr**
elementPrefix option to allow more cleaner configuration with alot of attributes. If elementPrefix present properties by default are treated as attributes (not as elements), and only properties that start with prefix are handled as elements (and also complex properties of cource too are tread as element despite the prefix).
- Updated docs.

### CODE REVIEW

**Comment by tlhunter** [comment]
Can you add tests to this PR?

**Comment by wclr** [comment]
and this?

**Comment by tlhunter** [comment]
There's an issue with the tests (Sad vs Bad) btw

**Comment by tlhunter** [comment]
Thanks for the PR, however I think it adds a bit too much complexity to the project.

Having another symbol prefix which changes behavior even more is something I'd like to avoid for now.

**Pull request closed without merging**
